# Funding options for RSP Framework
#
# If you'd like to support this project, you can add your sponsorship
# links here. This is optional and can be removed if not needed.

# github: [rahulsidpatil]
# patreon: username
# open_collective: project-name
# ko_fi: username
# custom: ['https://example.com']

# Note: Uncomment and update the relevant lines above to enable sponsorship
